### ISSUE TITLE
前端ui有bug

### ISSUE THREAD

**Issue by huanglian666** [jinwyp/one_click_script#267]
遇到了一个奇怪的问题，在chrome中添加入站报错
```html
vue.min.js:6 ReferenceError: inModal is not defined
    at wn.openAddInbound (inbounds:397:21)
    at He (vue.min.js:6:11384)
    at a.n (vue.min.js:6:13168)
    at He (vue.min.js:6:11384)
    at e.$emit (vue.min.js:6:34373)
    at a.handleClick (antd.min.js:2:855525)
    at He (vue.min.js:6:11384)
    at HTMLButtonElement.n (vue.min.js:6:13168)
    at Yr.o._wrapper (vue.min.js:6:48505)
```
但是使用safari访问就是正常

**Comment by jinwyp** [comment]
你是用哪个脚本? 安装的第几项?
